version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: space_sharks
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/space_sharks"
      JWT_SECRET: "dev_secret_change_me"
      BCRYPT_SALT: "10"
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    command: npm run start:dev

volumes:
  db-data:
